import { useId } from "react";

const UseIdHook = () => {
  const id = useId();

  return (
    <div>
      <form>
        <label htmlFor={id}>Enter your name:</label>
        <input id={id} type="text" placeholder="Your name" />
      </form>
    </div>
  );
};

export default UseIdHook;

// the label's "htmlFor" attribute is linked to the input's id attribute.
// This association allows screen readers to correctly identify the
// label for the input field, improving accessibility.

// to see the id generated in console log and inspect the element to see the
// id attribute of input field.

// the id generated by useId ensures that the label is correctly associated withthe input
